"""salt_iter_user

Revision ID: 09139d084ba4
Revises: e5b1b69fbd12
Create Date: 2022-06-15 17:34:04.199971

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '09139d084ba4'
down_revision = 'e5b1b69fbd12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.String(), nullable=False))
    op.add_column('users', sa.Column('iterations', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'iterations')
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###
