"""user_ip for auth

Revision ID: 2568a2ca11fc
Revises: ffd02046be0e
Create Date: 2022-06-16 16:48:45.407282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2568a2ca11fc'
down_revision = 'ffd02046be0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_history', sa.Column('user_ip', sa.String(), nullable=True))
    op.drop_column('auth_history', 'ip')
    op.create_unique_constraint(None, 'user_refresh_tokens', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_refresh_tokens', type_='unique')
    op.add_column('auth_history', sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('auth_history', 'user_ip')
    # ### end Alembic commands ###
