"""unique role name

Revision ID: 5fa32879f1b3
Revises: 2568a2ca11fc
Create Date: 2022-06-19 23:29:53.844422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa32879f1b3'
down_revision = '2568a2ca11fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_name_idx', 'roles', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name_idx', 'roles', type_='unique')
    # ### end Alembic commands ###
